# Generated by Django 2.1.5 on 2019-02-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillcategory',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
