# Generated by Django 2.1.5 on 2019-02-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
