# Generated by Django 2.1.5 on 2019-02-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communications',
            old_name='person',
            new_name='people',
        ),
    ]
